### ISSUE TITLE
Test framework fault tolerance needs to be improved

### ISSUE THREAD

**Issue by BarakSason** [gluster/glusto-tests#32]
As recent patch that was submitted has shown, the glusto-test framework is not sufficiently fault-tolerant.

The patch that was submitted for review caused the test to run an unreasonably long operation, which caused the test framework to hang in wait for operation to finish.
As a test framework is used to test and verify ongoing work, it is to be expected that faulty patches will be submitted to the system, and the system should handle these gracefully. A testing framework should possess a very high fault-tolerance.
The case that is described here poses a security risk as it opens the way for a complete shutdown of the CI system if a large number of long-running tests are submitted which will cause the test machines to hang (Similar to a DDoS attack).

Ideally, the test framework should set a timeout for each test and if a test continues to run longer than it's allocated time, the test framework will forcefully terminate the long-running test, end the regression gracefully and mark the run as a failure, without hanging.

**Comment by aloganat** [comment]
Hi Barak, we may hit this kind of scenario in a worst case scenario. Because we always test the script in local setup before sending the patch for review. If there is a system hang, then probably it could be a product bug. So leaving the system as it is will help us to debug the issue.  Also, we use this framework to automate non functional tests as well which usually takes longer time to complete.

**Comment by kshithijiyer** [comment]
Also to add to what @aloganat, we should keep that in mind that it's a functional test framework and not a unit test framework.
