### ISSUE TITLE
[RFE] Improve data verification mechanism

### ISSUE THREAD

**Issue by BarakSason** [gluster/glusto-tests#33]
A recent discussion brought into light a concern regarding the glusto-test framework's ability to perform data correctness verification on large data sets.
Currently data verification is performed using arequal checksum, which was observed to take an unreasonable amount of time while verifying large data sets.
An alternative mechanism may be used, which could speed up the data verification of large data sets and reduce the CI overall.

**Comment by kshithijiyer** [comment]
To fix this issue we have tried using crc32, sha512sum and md5sum but still, the time taken to verify data is taking too long.

**Comment by csabahenk** [comment]
One of the kind of input which probably could be checksummed more optimally are sparse files.

Relying on the `SEEK_DATA`/`SEEK_HOLE` _lseek(2)_ flags it would be possible to perform checksum of a sparse file in way that only parts of the file are read in which contain data.

In case of glusto, it shells out to arequal for checksumming, which in turn shells out to md5sum.

I did a quick search if md5sum, or a variant of it, or some other common checksum utility applies such an optimization. I found none that does. I found it strange, in these times when thin provisioning is pretty standard...

To see how much we could gain with this optimization, did the following quick test:

- A Ruby MD5 summer that uses the block size of the standard md5 tool, 1<<15:
  ```
  $ ruby -rdigest/md5 -e 'm=Digest::MD5.new; open($*[0]) {|f| while b=f.read(1<<15); m << b; end }; p m'
  ```
- A zero-read variant that assumes that the file passed to it contains only zeroes and its size is multiple of said blocksize:

  ```
  $ ruby -rdigest/md5 -e 'm=Digest::MD5.new; open($*[0]) {|f| b="\0"*(1<<15); (f.stat.size >> 15).times { m << b }}; p m'
  ```

On a 5g sparse file on ext4:

- general Ruby md5 summer: 11.3 sec
- md5sum (to see how much overhead the Ruby implementation has over the standard tool): 10.5 sec
- Ruby sparse file specific md5 summer: 8.5 sec

So definitely this is a usable optimization, even if the gain is not stellar.

**Comment by csabahenk** [comment]
I've been thinking further -- actually there is one established tool which is king at comparison by checksum, that is, rsync.

For actions that are expected to make changes in backend so that content is not changed (eg. rebalance), rsync could be utilized to verify that content is the same, by using snapshots.

- before going, create a gluster snapshot of the volume
- perform the action
- mount the snapshot
- remount the volume read-only
- do an rsync from snapshot mount to actual volume mount
  - if there is a difference, rsync tries to update the volume, which will fail due to read-only
  - if there is no difference, rsync will just finish happily

If gluster native snapshots are not possible/preferred to use for some reason, brick level snapshots with device mapper is also a possibility:

- create the volume with bricks on lvms
- snapshot (the lvms containing) the bricks
- create a "shadow" volume from brick snapshots
- perform action, then compare shadow volume with original volume similarly as above.

**Comment by kshithijiyer** [comment]
Sorry for the late reply, was jam packed with work for the last 2 weeks.

The rsync approach suggested @csabahenk looks good, I will try it out and revert back on that one if I am getting any problems.

I just have a couple of questions:
1. Wouldn't it cause any problems or failures if we use glusterfs snapshot?
2. Would it be a good idea to mount snapshot with readonly option or should we sent the glusterfs option to snapshot like we do in glusterfs?

For implementation side this doesn't really look like a big task as we already have rsync installed in CI, we just need to add code for creating snapshot, mounting it and do run the command.

**Comment by kshithijiyer** [comment]
@BarakSason @csabahenk I have tried the rsync approach. It looks like this solves the problem here. With the same workload I was able to do the check in 10s.
```
[root@dhcp43-80 rep]# time rsync /mnt/snap/ /mnt/rep/
skipping directory .

real	0m0.010s
user	0m0.004s
sys	0m0.004s
```

Steps followed to check:
1. Create a snapshot before performing the op(in this case it is add-brick).
2. Perform op on the volume.
3. Once op is complete set the volume to read-only and activate the snapshot and mount it.
4. Once snapshot is mounted perform rsync between the snapshot mount point and the volume mount point, if no data loss is see it'll exit with exit code `0`, if data is alerted the exit code will be something else which will case rsync to fail.  

 Currently I am just awaiting clarification from my previous comment. Once we have it, we are good to add it in the code and close this issue.

Thanks @csabahenk for the approach.

**Comment by csabahenk** [comment]
Hi @kshithijiyer,

- As of 1: I'm afraid it's up to see if any problem occurs :) I don't have a priori knowledge of issues with snapshot.
- As of 2: practically the difference between the read-only features is that the scope of the standard `ro` mount option is just the given mount, while the scope of the glusterfs option is the volume (so all kind of access to the volume will be subject to the read-only constraint). If in the test scenario the volume is accessed only from a single context, then it does not make a difference which way you make this access read-only.

**Comment by csabahenk** [comment]
@kshithijiyer However, I just spotted that your 10 sec result comes from a flawed invocation. rsync does not sync directories recursively unless explicitly asked (via `-r/--recurse` or `-a/--archive`). The _skipping directory ._ indeed indicates that rsync did not enter the file hierarchy.

**Comment by kshithijiyer** [comment]
@csabahenk The test was done for the I/O workload where 5000 sparse files are created on `/mnt/volname/` where there are no sub directories hierarchy present. That's why haven't added `-r` parameter, if we have a sub directory hierarchy present I do agree that we will have to run rsync with `-r` parameter and that would take more time.

**Comment by csabahenk** [comment]
rsync simply doesn't perform _readdir(2)_ only in recursive mode, so either `-r` is needed (maybe customized with some exclusions) or an explicit enumeration of the files in the command line. (My personal opinion is that the latter is more fragile, but YMMV.)

```
> mkdir dir{A,B}
> strace -efile,desc -y rsync dir{A,B} 2>&1 | grep dirA
execve("/usr/bin/rsync", ["rsync", "dirA", "dirB"], 0x7ffd187b5210 /* 24 vars */) = 0
lstat("dirA", {st_mode=S_IFDIR|0755, st_size=40, ...}) = 0
write(1<pipe:[170219703]>, "skipping directory dirA\n", 24skipping directory dirA
> strace -efile,desc -y rsync -r dir{A,B} 2>&1 | grep dirA
execve("/usr/bin/rsync", ["rsync", "-r", "dirA", "dirB"], 0x7ffe93672618 /* 24 vars */) = 0
lstat("dirA", {st_mode=S_IFDIR|0755, st_size=40, ...}) = 0
openat(AT_FDCWD, "dirA", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3</tmp/dirA>
fstat(3</tmp/dirA>, {st_mode=S_IFDIR|0755, st_size=40, ...}) = 0
getdents64(3</tmp/dirA>, 0x557f2011e5e0 /* 2 entries */, 32768) = 48
getdents64(3</tmp/dirA>, 0x557f2011e5e0 /* 0 entries */, 32768) = 0
close(3</tmp/dirA>)                     = 0
write(4<socket:[170214629]>, "#\0\0\7\240\31\4dirA\0(\0_\2170\245\360\301\356s1\355A\0\0\0\0\377d\0"..., 39) = 39
```

**Comment by csabahenk** [comment]
Sparse file support is also something that has to be explicitly enabled with `-S/--sparse`.

**Comment by kshithijiyer** [comment]
I had tried running `time rsync -r /mnt/arb_snap/ /mnt/arb/  --exclude=".*"` which didn't complete even after running it 2 days, after thinking threw it appeared to me even if we check if the files are same when compare to before it'll still work, hence tried out something like below:
```
# time for i in {1..5000};do timeout 180 rsync /mnt/arb_before/file_with_holes$i /mnt/arb/file_with_holes$i --temp-dir=/tmp/ --ignore-errors;done
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(644) [sender=3.1.3]
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at io.c(504) [generator=3.1.3]
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(644) [sender=3.1.3]
rsync: [sender] write error: Broken pipe (32)

real	7m28.681s
user	1m32.439s
sys	1m11.456s
```
This looks a lot promising as the time taken is:
```
real	7m28.681s
user	1m32.439s
sys	1m11.456s
```
in case of arbiter and in case of replica it is:
```
real	10m23.485s
user	2m22.652s
sys	1m28.508s
```

However I am unsure if the below errors are caused due to some misconfiguration or some issue:
```
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(644) [sender=3.1.3]
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at io.c(504) [generator=3.1.3]
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(644) [sender=3.1.3]
rsync: [sender] write error: Broken pipe (32)
```
Any clue on what's with the errors?

**Comment by aloganat** [comment]
Hi @BarakSason , @csabahenk , @kshithijiyer Could you provide an update on this issue?

So, the rsync approach that Csaba suggested works for all the cases or do we have an issue like what @kshithijiyer has mentioned in previous comment?

**Comment by kshithijiyer** [comment]
Hi @aloganat 
I had tried out running rysnc with `-r` parameter on the dir but that didn't complete even after 2 days, post which I tried using rsync by comparing the files directly. Was seeing a few errors messages but however it's working fine if we look overall.

@csabahenk @BarakSason should we go with this approach?

**Comment by BarakSason** [comment]
@kshithijiyer @aloganat 
The fact that errors are being seen and the fact that in the end this approach still takes an unreasonable amount of time leads me to believe that this approach is not satisfactory.

@csabahenk Please add your input as well.

**Comment by csabahenk** [comment]
As  of the errors mentioned in https://github.com/gluster/glusto-tests/issues/33#issuecomment-723757852 regarding running rsync file-by-file, it's nothing mysterious, they come from rsync jobs getting killed when they run out of time, as they are run under `timeout(1)`.

However, if not using rsync in recursive mode, I'd still suggest to use a single invocation, specifying the file list using the `--files-from` option.

rsync has a fine-grained debug facitlity, which is explained with `rsync --debug=help`. This should be used with appropriate parametrization to find out what's going on. Without going too elaborate, just passing a simple `-v` option (which equals to `--debug=all1`), and also `--progress` should reveal quite much.

I don't mind if the rsync approach is given up; yet if not, I heartily suggets to consult with the well written documentation how to observe and refine the process.

**Comment by kshithijiyer** [comment]
```
# time rsync /mnt/snapshot/ /mnt/testvol_replicated_glusterfs/ --temp-dir=/tmp/ --ignore-errors -v --progress --files-from=/mnt/file-list
building file list ...
5000 files to consider
file_with_holes2264
9,485,601,767,424   8%   53.30MB/s  511:20:37  ^C
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(644) [sender=3.1.3]
rsync: write failed on "/mnt/testvol_replicated_glusterfs/file_with_holes2264": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]

real    2774m26.246s
user    901m22.837s
sys     368m56.142s
```
@csabahenk When I try to run rsync with `--files-from` parameter, I am still seeing that the rsync isn't getting completed even after 36 hours? Could you please have a look at the above command and let us know if this can be optimized to run faster?

**Comment by kshithijiyer** [comment]
@csabahenk Did you get a chance to look at it?

**Comment by kshithijiyer** [comment]
We have tested rsync with file to file as per comment https://github.com/gluster/glusto-tests/issues/33#issuecomment-723757852, This can be accepted as it only increases the time by a small fraction.

**Comment by BarakSason** [comment]
@kshithijiyer I'm confused by you comment.
At https://github.com/gluster/glusto-tests/issues/33#issuecomment-723757852 you're mentioning that this attempt resulted in numerous errors and then in https://github.com/gluster/glusto-tests/issues/33#issuecomment-793814386 you're saying that this approach works (and in https://github.com/gluster/glusto-tests/issues/33#issuecomment-749347412 you're mentioning that it hasn't completed in 36 hours)?

Please clarify if the rsync approach works (within a reasonable amount of time) or not.

**Comment by kshithijiyer** [comment]
@BarakSason If you increase the timeout as mentioned in https://github.com/gluster/glusto-tests/issues/33#issuecomment-736737191 it works. 

Please refer the commands again in https://github.com/gluster/glusto-tests/issues/33#issuecomment-749347412 and https://github.com/gluster/glusto-tests/issues/33#issuecomment-723757852, they are different as in https://github.com/gluster/glusto-tests/issues/33#issuecomment-723757852 we are doing rsync through specific files as oppose to https://github.com/gluster/glusto-tests/issues/33#issuecomment-749347412 where we are using `-r` with `--files-from` option

**Comment by kshithijiyer** [comment]
> @kshithijiyer Please specify:
> 1 - Exactly what version of rsync command works?
```
# time for i in {1..5000};do timeout 200 rsync /mnt/arb_before/file_with_holes$i /mnt/arb/file_with_holes$i --temp-dir=/tmp/ --ignore-errors;done
```
> 2 - Are there errors in running it this way?
Not really.

> 3 - How long will it take for https://review.gluster.org/#/c/glusto-tests/+/25077/ to run and verify 5000 sparse files, each 110TB in size?
The test data posted in comments are done with the exact same workload.

**Comment by BarakSason** [comment]
@kshithijiyer 
From your previous comments it's not clear at all that you found a way that completes within a reasonable amount of time and without errors. All your comments reflect that there was some kind of issue with this approach (either time or errors).
If based on Csaba's recommendation you've managed to found an approach that satisfies all requirements, why this hasn't been integrated into gluso_test framework yet? This issue is open from October.

Please enhance the glusto_test framework and I'll adjust the number of files in https://review.gluster.org/#/c/glusto-tests/+/25077/ to 5000.

**Comment by aloganat** [comment]
Thanks @csabahenk for providing us the solution to resolve the issue.

hi @BarakSason ,
Could you please check comment [1] and comment [2], we waited quiet sometime to get ack for the steps that Kshithij had tried and to finalize the approach. Now, as the approach has been agreed by all of us, we will create a backlog in Jira for adding this logic in the glusto-tests library and to modify the existing DHT scripts to add this step wherever applicable. Based on QE's priority , we will pick this activity. On the other hand, to unblock your existing gerrit patch  https://review.gluster.org/#/c/glusto-tests/+/25077/ , please add the logic directly in the test script so that it will not be a blocker for merging it.

[1] - https://github.com/gluster/glusto-tests/issues/33#issuecomment-772349047
[2] - https://github.com/gluster/glusto-tests/issues/33#issuecomment-749347412

**Comment by BarakSason** [comment]
@aloganat As I said, to me it was not clear at all that a method which satisfies the requirements was found. Each comment mentioned some kinds of problem - either time or errors (as you can see at your [2] link, "I am still seeing that the rsync isn't getting completed even after 36 hours").
Regarding "we waited quiet sometime to get ack for the steps", some initiative might be expected - If no response was provided within a couple of days, surely a PM would move things along. I've received none.

Anyway, I'm happy we managed to find a method which satisfies all requirements.
As per my test fix, until the glusto_test code is enhanced, I can't make any updated to the fix as it'll get stuck in regression for a long time, so please let me know once you've modified the glust_test code and I'll update the test fix.
